//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appel_Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appel_Offre()
        {
            this.Contrat = new HashSet<Contrat>();
        }
    
        public int id_appOffre { get; set; }
        public int id_planning { get; set; }
        public double tonnage { get; set; }
        public System.DateTime date_Emission { get; set; }
        public System.DateTime date_livraison { get; set; }
        public System.DateTime date_creation { get; set; }
        public int nbr_bateaux { get; set; }
        public string observation { get; set; }
        public string type { get; set; }
        public string statut { get; set; }
    
        public virtual Planing_Previsionnel Planing_Previsionnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrat { get; set; }
    }
}
