//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centrale_Stock
    {
        public int Id_SCentrale { get; set; }
        public double stock_initial { get; set; }
        public int id_station { get; set; }
        public double stock_final { get; set; }
        public double stock_difference { get; set; }
        public double stock_ajustement { get; set; }
        public System.DateTime stock_date { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
