//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id_stock { get; set; }
        public decimal consommation { get; set; }
        public int id_bateau { get; set; }
        public double livraison { get; set; }
        public double decharge { get; set; }
        public System.DateTime date { get; set; }
        public double autonomie { get; set; }
    
        public virtual Bateau Bateau { get; set; }
    }
}
