//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Permissions
    {
        public int id_utilisateur { get; set; }
        public string nom_utilisateur { get; set; }
        public string nom_role { get; set; }
        public string nom_autorisation { get; set; }
        public string nom_application { get; set; }
    }
}
