//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBateau
    {
        public int id_bateau { get; set; }
        public string nom_bateau { get; set; }
        public int id_contrat { get; set; }
        public int id_origine { get; set; }
        public double tonnage { get; set; }
        public decimal valeur_calorifique { get; set; }
        public decimal cout { get; set; }
        public decimal frais_douane { get; set; }
        public double decharge { get; set; }
        public decimal prix_rendu { get; set; }
        public double assurance { get; set; }
        public string etat { get; set; }
        public string nom_origine { get; set; }
    }
}
