//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VContrat
    {
        public int id_contrat { get; set; }
        public string nom_contrat { get; set; }
        public int id_appOffre { get; set; }
        public int id_contDetails { get; set; }
        public string type { get; set; }
        public int nbr_cargaisons { get; set; }
        public decimal quantite_total { get; set; }
        public System.DateTime date_creation { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_fin { get; set; }
        public string statut { get; set; }
        public int id_fournisseur { get; set; }
        public string nom_fournisseur { get; set; }
    }
}
